### ISSUE TITLE
FR : Beeing able to override a DNS resolution for a domain in a http_checks

### ISSUE THREAD

**Issue by Al-25** [mcorbin/cabourotte#1]
Hello, 

It could be useful to add an option to the http_check configuration, allowing to force the resolution of the target domain to a specific IP address.

Usecase :
An architecture for a service (e.g website) with a primary and a secondary server, the secondary acting as a backup for redundancy/maintenance.
It could be great to being able to monitor the primary and the secondary at the same time, to be sure that the secondary is ready to be used when needed.
Which means an option is needed to force a specific ip adress in the http check for the secondary server.
 
Thanks for the tools BTW, it was (almost except this FR ;-) ) exactly the one that i was looking for my healthchecks !

Kr,

Al

**Comment by mcorbin** [comment]
Hello,

The `target` parameter for the HTTP (and TCP) healthcheck can be either a domain, an ipv4 or a IPv6. So if you use the IP instead of the domain in your healthcheck definition, it should work ;)

> Thanks for the tools BTW, it was (almost except this FR ;-) ) exactly the one that i was looking for my healthchecks !

Thanks ! I plan to add a lot of features in the next few weeks.

**Comment by Al-25** [comment]
Hello, 

Thanks for the reply.

Unfortunately, it will not work in my case (reverse proxy hosting multiple domain per IP), if i use the IP the RP won't know to which backend send it without the right domain (except if it's possible to modify the Host header in the check to specify a domain instead of the IP),

Any other idea by any chance ?

"Thanks ! I plan to add a lot of features in the next few weeks."
Will follow that, for sure !

**Comment by mcorbin** [comment]
I plan to add custom headers support for the HTTP healthchecks soon (it's actually already implemented on master, I just have to create a new release).

**Comment by mcorbin** [comment]
I'm closing this issue because new options are availables (https://cabourotte.mcorbin.fr/installation/configuration/).
